"""OpenGL 1.x on Android, backed by gl4es.

GENERATED by tools/generate_gl_shim.py from pyglet 1.5.31 - do not edit.

The game is written against desktop OpenGL 1.x: a matrix stack, display
lists, fixed-function lighting, fog, alpha test, GL_QUADS and client-side
vertex arrays. Android exposes only OpenGL ES, where none of that exists.
gl4es implements GL 1.5 over GLES2, so this module is a ctypes binding to
it rather than an emulation of it.

Importing this module must not touch GL: the game's Cython modules import
pyglet.gl at their own import time, long before a context exists, and that
is exactly what crashed the first APK. Call initialize() once the context
is current instead.
"""

import ctypes
import os
import sys
from ctypes import (CFUNCTYPE, POINTER, c_char, c_double, c_float, c_int,
                    c_int64, c_short, c_ubyte, c_uint, c_uint64, c_ushort,
                    c_void_p)

# pyglet resolves this per platform; on the ABIs we ship it is the native
# pointer-sized signed integer.
c_ptrdiff_t = ctypes.c_ssize_t

#: Entry points gl4es turned out not to export. Empty is the healthy state;
#: anything listed here is a call the game may make that will do nothing.
MISSING = []

#: Set by initialize() so a caller can tell a working binding from a stub.
INITIALIZED = False

_CANDIDATES = ('libgl4es.so', 'libGL.so.1', 'libGL.so')


def _load():
    # The override exists so tools/check_gl_shim.py can import this module
    # off-device against a stub, which is the only way to catch a bad name
    # order or a malformed signature before a 15-minute build.
    override = os.environ.get('GL4ES_LIBRARY')
    errors = []
    for name in ((override,) if override else _CANDIDATES):
        try:
            return ctypes.CDLL(name)
        except OSError as exc:
            errors.append('%s: %s' % (name, exc))
    raise ImportError('gl4es not found (%s)' % '; '.join(errors))


_lib = _load()


def _fn(name, restype, argtypes):
    """Bind one entry point, tolerating absence.

    A missing symbol must not raise at import time: one unimplemented call
    should cost that call, not the whole game, and the name is far more
    useful reported from the device than as an ImportError nobody can see.
    """
    try:
        func = getattr(_lib, name)
    except AttributeError:
        MISSING.append(name)

        def absent(*_args):
            return 0

        absent.__name__ = name
        return absent

    func.restype = restype
    func.argtypes = argtypes
    return func


# Type aliases, in pyglet's own order: some are defined in
# terms of earlier ones, so this order is load-bearing.
GLenum = c_uint
GLboolean = c_ubyte
GLbitfield = c_uint
GLvoid = None
GLbyte = c_char
GLshort = c_short
GLint = c_int
GLubyte = c_ubyte
GLushort = c_ushort
GLuint = c_uint
GLsizei = c_int
GLfloat = c_float
GLclampf = c_float
GLdouble = c_double
GLclampd = c_double
GLeglImageOES = POINTER(None)
GLchar = c_char
GLintptr = c_ptrdiff_t
GLsizeiptr = c_ptrdiff_t
GLintptrARB = c_ptrdiff_t
GLsizeiptrARB = c_ptrdiff_t
GLcharARB = c_char
GLhandleARB = c_uint
GLhalfARB = c_ushort
GLhalfNV = c_ushort
GLint64EXT = c_int64
GLuint64EXT = c_uint64
GLint64 = c_int64
GLuint64 = c_uint64
GLDEBUGPROCARB = CFUNCTYPE(None, GLenum, GLenum, GLuint, GLenum, GLsizei, POINTER(GLchar), POINTER(GLvoid))
GLDEBUGPROCAMD = CFUNCTYPE(None, GLuint, GLenum, GLenum, GLsizei, POINTER(GLchar), POINTER(GLvoid))


# Enumerants.
GL_ALPHA_TEST = 3008
GL_AMBIENT = 4608
GL_AMBIENT_AND_DIFFUSE = 5634
GL_ARRAY_BUFFER = 34962
GL_BACK = 1029
GL_BLEND = 3042
GL_CLAMP = 10496
GL_COLOR_ARRAY = 32886
GL_COLOR_BUFFER_BIT = 16384
GL_COLOR_MATERIAL = 2903
GL_COMPILE = 4864
GL_CONTEXT_PROFILE_MASK = 37158
GL_CULL_FACE = 2884
GL_DEPTH_BUFFER_BIT = 256
GL_DEPTH_TEST = 2929
GL_DIFFUSE = 4609
GL_DST_ALPHA = 772
GL_DST_COLOR = 774
GL_EQUAL = 514
GL_EXP = 2048
GL_EXTENSIONS = 7939
GL_FLOAT = 5126
GL_FOG = 2912
GL_FOG_COLOR = 2918
GL_FOG_DENSITY = 2914
GL_FOG_END = 2916
GL_FOG_MODE = 2917
GL_FOG_START = 2915
GL_FRONT = 1028
GL_FRONT_AND_BACK = 1032
GL_GREATER = 516
GL_INT = 5124
GL_LEQUAL = 515
GL_LIGHT0 = 16384
GL_LIGHT1 = 16385
GL_LIGHTING = 2896
GL_LIGHT_MODEL_AMBIENT = 2899
GL_LINEAR = 9729
GL_LINES = 1
GL_LINE_LOOP = 2
GL_LINE_STRIP = 3
GL_MODELVIEW = 5888
GL_MODELVIEW_MATRIX = 2982
GL_NEAREST = 9728
GL_NORMALIZE = 2977
GL_ONE = 1
GL_ONE_MINUS_DST_COLOR = 775
GL_ONE_MINUS_SRC_ALPHA = 771
GL_ONE_MINUS_SRC_COLOR = 769
GL_PACK_ALIGNMENT = 3333
GL_POINTS = 0
GL_POSITION = 4611
GL_PROJECTION = 5889
GL_PROJECTION_MATRIX = 2983
GL_QUADS = 7
GL_QUERY_COUNTER_BITS = 34916
GL_QUERY_RESULT = 34918
GL_QUERY_RESULT_AVAILABLE = 34919
GL_RENDERER = 7937
GL_REPEAT = 10497
GL_RGB = 6407
GL_RGBA = 6408
GL_SAMPLES_PASSED = 35092
GL_SMOOTH = 7425
GL_SPECULAR = 4610
GL_SRC_ALPHA = 770
GL_SRC_COLOR = 768
GL_STREAM_DRAW = 35040
GL_TEXTURE_2D = 3553
GL_TEXTURE_COORD_ARRAY = 32888
GL_TEXTURE_MAG_FILTER = 10240
GL_TEXTURE_MIN_FILTER = 10241
GL_TEXTURE_WRAP_S = 10242
GL_TEXTURE_WRAP_T = 10243
GL_TRIANGLE_FAN = 6
GL_UNSIGNED_BYTE = 5121
GL_VENDOR = 7936
GL_VERSION = 7938
GL_VERTEX_ARRAY = 32884


# Entry points. _fn() records anything gl4es does not export
# in MISSING rather than failing the import, so a gap shows up
# as a diagnostic instead of a crash on a black screen.
glAlphaFunc = _fn('glAlphaFunc', None, [GLenum, GLclampf])
glBeginQueryARB = _fn('glBeginQueryARB', None, [GLenum, GLuint])
glBindBufferARB = _fn('glBindBufferARB', None, [GLenum, GLuint])
glBindTexture = _fn('glBindTexture', None, [GLenum, GLuint])
glBlendFunc = _fn('glBlendFunc', None, [GLenum, GLenum])
glBufferDataARB = _fn('glBufferDataARB', None, [GLenum, GLsizeiptrARB, POINTER(GLvoid), GLenum])
glCallList = _fn('glCallList', None, [GLuint])
glCallLists = _fn('glCallLists', None, [GLsizei, GLenum, POINTER(GLvoid)])
glClear = _fn('glClear', None, [GLbitfield])
glClearColor = _fn('glClearColor', None, [GLclampf, GLclampf, GLclampf, GLclampf])
glClearDepth = _fn('glClearDepth', None, [GLclampd])
glColor3f = _fn('glColor3f', None, [GLfloat, GLfloat, GLfloat])
glColor4f = _fn('glColor4f', None, [GLfloat, GLfloat, GLfloat, GLfloat])
glColor4ub = _fn('glColor4ub', None, [GLubyte, GLubyte, GLubyte, GLubyte])
glColorMask = _fn('glColorMask', None, [GLboolean, GLboolean, GLboolean, GLboolean])
glColorMaterial = _fn('glColorMaterial', None, [GLenum, GLenum])
glColorPointer = _fn('glColorPointer', None, [GLint, GLenum, GLsizei, POINTER(GLvoid)])
glCullFace = _fn('glCullFace', None, [GLenum])
glDeleteTextures = _fn('glDeleteTextures', None, [GLsizei, POINTER(GLuint)])
glDepthFunc = _fn('glDepthFunc', None, [GLenum])
glDepthMask = _fn('glDepthMask', None, [GLboolean])
glDisable = _fn('glDisable', None, [GLenum])
glDisableClientState = _fn('glDisableClientState', None, [GLenum])
glDrawArrays = _fn('glDrawArrays', None, [GLenum, GLint, GLsizei])
glDrawElements = _fn('glDrawElements', None, [GLenum, GLsizei, GLenum, POINTER(GLvoid)])
glEnable = _fn('glEnable', None, [GLenum])
glEnableClientState = _fn('glEnableClientState', None, [GLenum])
glEndList = _fn('glEndList', None, [])
glEndQueryARB = _fn('glEndQueryARB', None, [GLenum])
glFogf = _fn('glFogf', None, [GLenum, GLfloat])
glFogfv = _fn('glFogfv', None, [GLenum, POINTER(GLfloat)])
glFogi = _fn('glFogi', None, [GLenum, GLint])
glFrustum = _fn('glFrustum', None, [GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble])
glGenBuffersARB = _fn('glGenBuffersARB', None, [GLsizei, POINTER(GLuint)])
glGenLists = _fn('glGenLists', GLuint, [GLsizei])
glGenQueriesARB = _fn('glGenQueriesARB', None, [GLsizei, POINTER(GLuint)])
glGenTextures = _fn('glGenTextures', None, [GLsizei, POINTER(GLuint)])
glGetError = _fn('glGetError', GLenum, [])
glGetFloatv = _fn('glGetFloatv', None, [GLenum, POINTER(GLfloat)])
glGetIntegerv = _fn('glGetIntegerv', None, [GLenum, POINTER(GLint)])
glGetQueryObjectivARB = _fn('glGetQueryObjectivARB', None, [GLuint, GLenum, POINTER(GLint)])
glGetString = _fn('glGetString', POINTER(GLubyte), [GLenum])
glInterleavedArrays = _fn('glInterleavedArrays', None, [GLenum, GLsizei, POINTER(GLvoid)])
glLightModelfv = _fn('glLightModelfv', None, [GLenum, POINTER(GLfloat)])
glLightfv = _fn('glLightfv', None, [GLenum, GLenum, POINTER(GLfloat)])
glLineWidth = _fn('glLineWidth', None, [GLfloat])
glLoadIdentity = _fn('glLoadIdentity', None, [])
glMatrixMode = _fn('glMatrixMode', None, [GLenum])
glMultMatrixf = _fn('glMultMatrixf', None, [POINTER(GLfloat)])
glNewList = _fn('glNewList', None, [GLuint, GLenum])
glNormal3f = _fn('glNormal3f', None, [GLfloat, GLfloat, GLfloat])
glNormalPointer = _fn('glNormalPointer', None, [GLenum, GLsizei, POINTER(GLvoid)])
glOrtho = _fn('glOrtho', None, [GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble])
glPixelStorei = _fn('glPixelStorei', None, [GLenum, GLint])
glPopMatrix = _fn('glPopMatrix', None, [])
glPushMatrix = _fn('glPushMatrix', None, [])
glReadPixels = _fn('glReadPixels', None, [GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, POINTER(GLvoid)])
glRotatef = _fn('glRotatef', None, [GLfloat, GLfloat, GLfloat, GLfloat])
glScalef = _fn('glScalef', None, [GLfloat, GLfloat, GLfloat])
glShadeModel = _fn('glShadeModel', None, [GLenum])
glTexCoordPointer = _fn('glTexCoordPointer', None, [GLint, GLenum, GLsizei, POINTER(GLvoid)])
glTexImage2D = _fn('glTexImage2D', None, [GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, POINTER(GLvoid)])
glTexParameteri = _fn('glTexParameteri', None, [GLenum, GLenum, GLint])
glTexSubImage2D = _fn('glTexSubImage2D', None, [GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, POINTER(GLvoid)])
glTranslatef = _fn('glTranslatef', None, [GLfloat, GLfloat, GLfloat])
glVertexPointer = _fn('glVertexPointer', None, [GLint, GLenum, GLsizei, POINTER(GLvoid)])
glViewport = _fn('glViewport', None, [GLint, GLint, GLsizei, GLsizei])


# ---------------------------------------------------------------------------
# gl4es start-up, and the bits of pyglet's API the game reaches for that are
# not GL entry points at all.
# ---------------------------------------------------------------------------

_FB_SIZE_CB = CFUNCTYPE(None, POINTER(c_int), POINTER(c_int))

#: Reported to gl4es as the size of the default framebuffer. initialize()
#: overwrites it with the real window size.
framebuffer_size = [1280, 720]


def _get_main_fb_size(width, height):
    width[0], height[0] = framebuffer_size


_fb_size_callback = _FB_SIZE_CB(_get_main_fb_size)  # kept alive deliberately


def initialize(size=None):
    """Start gl4es. The GL context must already be current.

    Built with NOEGL, gl4es does not create or look up a context itself -
    SDL has already made one - but it still needs a way to resolve GLES
    entry points and to learn the default framebuffer size, so both are
    handed to it here.
    """
    global INITIALIZED
    if INITIALIZED:
        return True
    if size:
        framebuffer_size[:] = [int(size[0]), int(size[1])]

    egl = ctypes.CDLL('libEGL.so')
    _lib.set_getprocaddress.argtypes = [c_void_p]
    _lib.set_getprocaddress(ctypes.cast(egl.eglGetProcAddress, c_void_p))
    _lib.set_getmainfbsize.argtypes = [_FB_SIZE_CB]
    _lib.set_getmainfbsize(_fb_size_callback)

    # Absent when gl4es was built with its init constructor left on, in
    # which case it initialised itself at dlopen and there is nothing to
    # call. The recipe disables that, but a binary built either way should
    # not take the app down here.
    try:
        _lib.initialize_gl4es()
    except AttributeError:
        MISSING.append('initialize_gl4es')

    INITIALIZED = True
    return True


def _string(name):
    value = ctypes.cast(glGetString(name), ctypes.c_char_p).value
    return value.decode('utf-8', 'replace') if value else ''


class GLInfo:
    """pyglet.gl.gl_info, narrowed to what the game asks it.

    Two answers here are deliberate rather than discovered. Occlusion
    queries are reported absent: gl4es does not implement the ARB entry
    points, and the game's only use of them is an optimisation it skips
    cleanly when the extension is missing. Versions above 1.5 are reported
    absent for the same reason - the one 3.2 branch in Minecraft.py asks
    for a core-profile mask that means nothing here.
    """

    #: Anything above this makes the game take a path gl4es cannot serve.
    MAX_VERSION = (1, 5)

    def get_version(self):
        return _string(GL_VERSION) or '1.5 gl4es'

    def get_renderer(self):
        return _string(GL_RENDERER)

    def get_vendor(self):
        return _string(GL_VENDOR)

    def get_extensions(self):
        return _string(GL_EXTENSIONS).split()

    def have_extension(self, name):
        if 'occlusion_query' in name:
            return False
        return name in self.get_extensions()

    def have_version(self, major, minor=0):
        return (major, minor) <= self.MAX_VERSION


gl_info = GLInfo()
