"""OpenGL 1.x on Android, backed by gl4es.

GENERATED by tools/generate_gl_shim.py from pyglet 1.5.31 - do not edit.

The game is written against desktop OpenGL 1.x: a matrix stack, display
lists, fixed-function lighting, fog, alpha test, GL_QUADS and client-side
vertex arrays. Android exposes only OpenGL ES, where none of that exists.
gl4es implements GL 1.5 over GLES2, so this module is a ctypes binding to
it rather than an emulation of it.

Importing this module must not touch GL: the game's Cython modules import
pyglet.gl at their own import time, long before a context exists, and that
is exactly what crashed the first APK. Call initialize() once the context
is current instead.
"""

import ctypes
import os
import sys
from ctypes import (CFUNCTYPE, POINTER, c_char, c_double, c_float, c_int,
                    c_int64, c_short, c_ubyte, c_uint, c_uint64, c_ushort,
                    c_void_p)

# pyglet resolves this per platform; on the ABIs we ship it is the native
# pointer-sized signed integer.
c_ptrdiff_t = ctypes.c_ssize_t

#: Entry points gl4es turned out not to export. Empty is the healthy state;
#: anything listed here is a call the game may make that will do nothing.
MISSING = []

#: Set by initialize() so a caller can tell a working binding from a stub.
INITIALIZED = False

_CANDIDATES = ('libgl4es.so', 'libGL.so.1', 'libGL.so')


def _load():
    # The override exists so tools/check_gl_shim.py can import this module
    # off-device against a stub, which is the only way to catch a bad name
    # order or a malformed signature before a 15-minute build.
    override = os.environ.get('GL4ES_LIBRARY')
    errors = []
    for name in ((override,) if override else _CANDIDATES):
        try:
            return ctypes.CDLL(name)
        except OSError as exc:
            errors.append('%s: %s' % (name, exc))
    raise ImportError('gl4es not found (%s)' % '; '.join(errors))


_lib = _load()


def _fn(name, restype, argtypes):
    """Bind one entry point, tolerating absence.

    A missing symbol must not raise at import time: one unimplemented call
    should cost that call, not the whole game, and the name is far more
    useful reported from the device than as an ImportError nobody can see.
    """
    try:
        func = getattr(_lib, name)
    except AttributeError:
        MISSING.append(name)

        def absent(*_args):
            return 0

        absent.__name__ = name
        return absent

    func.restype = restype
    func.argtypes = argtypes
    return func


